version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test
  upload-to-codecov:
    name: Upload coverage reports to Codecov
    command: |
        curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"token": "${{ secrets.CODECOV_TOKEN }}", "flags": "all"}' \
            https://codecov.io/upload/v4

workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
        - codecov-upload