version: 8.0

# Define all the job we need to run the project
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test
  codecov-upload:
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t 5d986fcd-2a5a-4a80-bf24-5e858832ebc4
          when: always

# Job
workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
        - codecov-upload