version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test
      - store_artifacts:
          path: target
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - codecov/upload

 checkstyle-job:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/checkstyle-result.xml
      - run:
          name: Generate Checkstyle Badge
          command: echo "Checkstyle Passed" > checkstyle-badge.txt
      - store_artifacts:
          path: checkstyle-badge.txt

# Job
workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - checkstyle-job:
        requires:
            - build-and-test